[workspace]
members = [
    "libs/common",
    "libs/query_parser",
    "services/query-api",
    "services/metrics-api"
]
resolver = "2"

[workspace.dependencies]
thiserror = "2.0.12"
serde = { version="1.0.219", features=["derive"] }
